[project]
name        = "typenaut"
description = "Typst metaprogramming in python"
authors     = [{name="Tremeschin"}]
version     = "0.0.2"
readme      = "readme.md"
license     = "MIT"
requires-python = ">=3.10"
dependencies = [
    "attrs",
    "pillow",
    "pypdfium2",
    "typst",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
