import atexit
import gc
import shutil
import subprocess
from collections.abc import Iterable
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Optional

import typst
from attrs import Factory, define
from PIL.Image import Image as ImageType

from typenaut.core.length import Length, length
from typenaut.module import Composite
from typenaut.utils import mkdir

# Ensure workspace is cleaned at exit
atexit.register(gc.collect)

__all__ = ["Document"]

@define
class Margin(Composite):
    right:  Length = Factory(length.auto)
    left:   Length = Factory(length.auto)
    top:    Length = Factory(length.auto)
    bottom: Length = Factory(length.auto)

    def typst(self) -> Iterable[str]:
        yield f"#set page(margin: ("
        yield   f"right:  {self.right.code()},"
        yield   f"left:   {self.left.code()},"
        yield   f"top:    {self.top.code()},"
        yield   f"bottom: {self.bottom.code()},"
        yield f"))"


@define
class Document(Composite):
    margin: Margin = Factory(Margin, takes_self=True)

    _workspace: TemporaryDirectory = Factory(lambda: TemporaryDirectory(prefix=f"{__package__}-"))
    """Temporary directory to store document files, cleaned up on garbage collection"""

    @property
    def workspace(self) -> Path:
        return Path(self._workspace.name)

    def __attrs_post_init__(self):
        Composite.__attrs_post_init__(self)

    # -------------------------------- #

    def typst(self) -> Iterable[str]:
        yield "// This file was programmatically generated by:"
        yield "// • https://github.com/BrokenSource/Typenaut"

        # Organize imports at the start
        for module in self.traverse():
            yield from module.imports()

        for child in self.children:
            yield from child.typst()

    def code(self) -> str:
        code = '\n'.join(self.typst())
        code = '\n'.join(filter(None, code.splitlines()))
        self._typ.write_text(code)

        # Optional code formatting if available
        if (typstyle := shutil.which("typstyle")):
            subprocess.run((typstyle, "-i", str(self._typ)))

        return self._typ.read_text()

    def pdf(self,
        output: Optional[Path]=None,
    ) -> bytes:
        self.code()
        return typst.compile(
            root=self.workspace,
            input=self._typ,
            output=output,
            format="pdf",
        )

    def png(self,
        ppi: int=144,
    ) -> ImageType:
        raise NotImplementedError

    # -------------------------------- #
    # Static directories and files

    @property
    def _typ(self) -> Path:
        return (self.workspace/"main.typ")

    @property
    def images(self) -> Path:
        return mkdir(self.workspace/"images")
